language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit
